### ISSUE TITLE
NetStandrd / dotnet core support

### ISSUE THREAD

**Issue by nothingmn** [vivet/GoogleApi#10]

**Comment by vivet** [comment]
I will look into it soon.
Thanks for the feedback

**Comment by vivet** [comment]
As far as i can see VS2015 is required for building with .net core. 
This will be a little while before i upgrade and build for this framework.

**Comment by nothingmn** [comment]
FYI, the only requirement would be the command line tools, under Mac, Win and Linux

https://www.microsoft.com/net/core#windowscmd

**Comment by vivet** [comment]
Hi

Will give it an extra look, but wanted to avoid having to build outside
visual studio, to ease the pain when publishing new nuget packages.

Will get back to you as soon as possible.

On Nov 21, 2016 18:29, "Rob Chartier" <notifications@github.com> wrote:

FYI, the only requirement would be the command line tools, under Mac, Win
and Linux

https://www.microsoft.com/net/core#windowscmd

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/vivet/GoogleApi/issues/10#issuecomment-261989043>, or mute
the thread

**Comment by vivet** [comment]
Hi

Sorry for the long waiting time.
I have tried building for dotnet core, though not successfully. Some refactoring is required at the usage of System.Net.WebClient. 

Currently i don't have too much time, so if you want support for dotnet through me a PR with the required changes.
