### ISSUE TITLE
Google are deprecating multiple types in Place Searches

### ISSUE THREAD

**Issue by alowdon** [vivet/GoogleApi#12]
As detailed at https://developers.google.com/places/web-service/search, Google are deprecating the ability to use multiple types when performing Nearby Searches, but this API only offers a `Types` property on the `PlacesNearBySearchRequest` which doesn't give me confidence that it has been updated accordingly. Multiple types will stop working on February 16, 2017. Is there a plan to fix this?

**Comment by vivet** [comment]
Will check it out, and fix before.
I must have missed the Google email.
Will let you know when I have pushed a fix.

On Jan 9, 2017 14:51, "Adrian Lowdon" <notifications@github.com> wrote:

As detailed at https://developers.google.com/places/web-service/search,
Google are deprecating the ability to use multiple types when performing
Nearby Searches, but this API only offers a Types property on the
PlacesNearBySearchRequest which doesn't give me confidence that it has been
updated accordingly. Multiple types will stop working on February 16, 2017.
Is there a plan to fix this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/vivet/GoogleApi/issues/12>, or mute the thread

**Comment by alowdon** [comment]
Thanks @vivet!

**Comment by vivet** [comment]
Its solved and new Nuget package published.

**Comment by alowdon** [comment]
Thanks so much for the speedy response and fix :)

**Comment by alowdon** [comment]
@vivet Unfortunately I've spotted a problem with the update you provided. The logic for validating the request still refers to the `Types` field, which now it has been removed will be null, so this line throws an exception:

    if (this.Rankby == Ranking.Distance && string.IsNullOrWhiteSpace(this.Name) && !this.Types.Any())
        throw new ArgumentException("If rankby=distance is specified, then one or more of keyword, name, or types is required.");

**Comment by vivet** [comment]
Will look into it one of the next days

**Comment by vivet** [comment]
Fixed but untested. 
I am a bit bust at the moment, so i wont be able to test it before within a few weeks.
Feel free to try the latest changes and let me know if you still have issues.

**Comment by vivet** [comment]
Tested now :-)
