### ISSUE TITLE
Parallel Requests / Batch

### ISSUE THREAD

**Issue by dotnetshadow** [vivet/GoogleApi#144]
Hi there,

Great Library, keep up the good work. 
Just wondering if there is an example of making parallel requests for example using **DistanceMatrix api**

Currently I make a request using this:
`var response = GoogleMaps.DistanceMatrix.Query(request);`

But I have a need to compare a location to 10 other locations, to get the distance etc. So currently I have a loop and just make one request to google at a time. Is there a way send multiple requests at once?

Location1 to Location2
Location1 to Location3
Location1 to Location4 
...
...
Location1 to Location10

**Comment by vivet** [comment]
Hi
Yes there are a limit for both origins and destinations. If i remember correctly its about 20 x 20, but I think you can see that in the triple-slash doc. Otherwise check the Google docs for Distance Matrix. Also be aware that Google has some requests limits, based on the number of returned elements. Such as max 800 elements per 10 seconds, or similar. In 20 x 20 example, that would be 400 elements returns. 

Hope it makes sense.
Also, please star my library if you like it.

Have a nice day.

**Comment by vivet** [comment]
Hi
Did you manage to figure it out?

**Comment by vivet** [comment]
It's documentation on top of properties, classes, methods, etc in C#.
Look here for the distance matrix request: https://github.com/vivet/GoogleApi/blob/master/GoogleApi/Entities/Maps/DistanceMatrix/Request/DistanceMatrixRequest.cs
When you hover the different properties, classes, methods etc, you will see the documentation.
Though i see the max origins and destinations isn't part of the triple-slash docs. So check on Google docs. 

Piece of advice, generally try to make smaller requests. It will be faster, and cost you much less money.

**Comment by dotnetshadow** [comment]
Cheers thanks for that, I will definitely look at the /// and google docs. Once again a great library 👍

**Comment by vivet** [comment]
I will close the issue
Hope you figured it out 😃
