### ISSUE TITLE
Providing a more detailed documentation

### ISSUE THREAD

**Issue by kesarling** [vivet/GoogleApi#231]
@vivet, I have been trying to use the API for almost a week now, after the old "Javascript" did not work out very well with my App. However, unfortunately, there is absolutely no documentation available on how to use the project. The only little I could find describes ways to Create a new direction request, but no documentation is available on the basics of using the API, like creating a map or placing a marker on the map (et al). It would be really nice if this project were to be documented (something like an unrelated project I have [here](https://github.com/kesarling/docker-microservices))

**Comment by vivet** [comment]
Hi
The project is documented... let me explain.
The project is so simple to use, that only docs that should be needed is the readme of the project. That is not to sound cocky, when you have a problem, but I think you have misunderstood the purpose of the Library, since you are comparing it with JS, and this library is a wrapper for Google's REST api's, and not JS. Additionally, all Google's own documentation is valid, so try seek out that.

**Comment by kesarling** [comment]
Hmm... I guess, I did misunderstand the project then... (err, newb misunderstandings😅). So, I am supposed to use this in conjunction with Google's JS, correct?

**Comment by vivet** [comment]
Hi
I am not expert in JS, so honestly I don't know how that map works, but this library is for request / response. So you pass a request and get a response, and what you do with that, is outside the scope of this project. I suppose you are using the static maps?

**Comment by kesarling** [comment]
Yes. Although, I am facing stupid issues while trying to set a Marker on the map (but I guess that's an altogether different discussion). Anyways, you may as well go ahead and close this issue. Sorry to trouble unnecessarily.

**Comment by vivet** [comment]
No problem. Good luck.
