### ISSUE TITLE
Add response headers to GoogleApiException

### ISSUE THREAD

**Issue by sschutten** [vivet/GoogleApi#279]
It would be nice to have access to the response headers in the `GoogleApiException`. For example in the case where the rate limit of the Google API is reached, the API will respond with a `429 (Too Many Requests)` and include a `Retry-After` header with information when to retry. The [EnsureSuccessStatusCode](https://github.com/vivet/GoogleApi/blob/1c1c0dd7aa85db6b76134e062d7ff6566f81146a/GoogleApi/HttpEngine.cs#L347) that is used throws a `RequestMessageException` that is set as the inner exception of the `GoogleApiException`. Unfortunately the `RequestMessageException` doesn't contain the reponse headers.

**Comment by vivet** [comment]
Hi
I am about to do a make-over of the HttpEngine, and will look into this at the same time.

**Comment by vivet** [comment]
Hi
I looked into the issue. I triggered the QueryOverLimit, which correctly throws a GoogleApiException, based on the returned response status. What you are experiencing is a http request limit from Google's Webserver, which only happens when you are doing really excessive requesting. The Retry-After will most likely shows a future of milliseconds. Basically, this shouldn't happen, why I have decided not to change anything.

I think you need to revisit your calling code, and consider how you are using the Google Api's. You can paste the calling code, and maybe I can assist.
