### ISSUE TITLE
Places auto complete bug multi types

### ISSUE THREAD

**Issue by Kiryuumaru** [vivet/GoogleApi#327]
Hi, I tried this code below and it throws "INVALID_REQUEST". I tested it and this only exists in multi types query.
```
await GoogleApi.GooglePlaces.AutoComplete.QueryAsync(new PlacesAutoCompleteRequest
            {
                Key = apiKey,
                Input = input,
                Types = new List<RestrictPlaceType>() {
                    RestrictPlaceType.Address,
                    RestrictPlaceType.Establishment
                }
            });
```

**Comment by vivet** [comment]
Hi
I will give it a try.

**Comment by vivet** [comment]
I have looked into the issue, and it's always a bit complicated dealing with Google place types.
GoogleApi is missing a lot of values in the enum, as described here: https://developers.google.com/maps/documentation/places/web-service/supported_types

"Only a single type from Table 3 is allowed in the request. If you do specify a value from Table 3, you cannot specify a value from Table 1 or Table 2."

And that is actually what is wrong with your request, though since you only have the option of settings types from table 3, you can only specify one at the momen
I will add all the missing places, but there is a tricky thing.

I will need to think a bit about if I can handle the rules of the tables.

I hope to have a fix beginning of next week.

**Comment by vivet** [comment]
I have published an updated NuGet, fixing it.
