### ISSUE TITLE
Could not parse ramp

### ISSUE THREAD

**Issue by Trojaner** [vivet/GoogleApi#329]
After upgrading from 4.2.6 to 4.5.2 we started getting the following error in directions API:
`GoogleApi.Exceptions.GoogleApiException: Could not parse ramp`

Related code
```c#
        var request = new DirectionsRequest
        {
            Key = GetApiKey(),
            Origin = new LocationEx(new CoordinateEx(origin.Latitude, origin.Longitude)),
            Destination = new LocationEx(new CoordinateEx(destination.Latitude, destination.Longitude))
        };

        var response = await GoogleMaps.Directions.QueryAsync(request); <-- HERE
```

This is a regression bug.

**Comment by vivet** [comment]
I will have a look.
Probably a new type frim Google

**Comment by vivet** [comment]
Hi 
Can you supply the coordinates, so I can reproduce the exception

**Comment by RobinVangampelaere** [comment]
[response.txt](https://github.com/vivet/GoogleApi/files/10731336/response.txt)
@vivet Any news on this?

I can reproduce this by using the Directions API:
- Start: 'Pastorijstraat 1a, Moorslede, België'
- End: 'Beheerstraat 10, Kortrijk, [België']()

I added the result in the attachments where you find the result on line 257, which is weird because it is not documented: https://developers.google.com/maps/documentation/routes_preferred/reference/rest/Shared.Types/Maneuver

**Comment by vivet** [comment]
Google is not always so good at adding new types like the Maneuver.

I have added ramp to the Directions response ManeuverAction.
New NuGet v4.5.3 is publishing now, and should be ready in 5-10 min
