### ISSUE TITLE
Unable to use in Visual Studio 2012

### ISSUE THREAD

**Issue by histerical** [vivet/GoogleApi#38]
I am unable to use the nuget package for this API because when I try to run, it is unable to get the correct version of Newtonsoft.Json because VS 2012 can only go up to 9.6. Unforunately I can't get a different version of VS because of my work, we are upgrading next year to 2017. Below is the exception:

"An unhandled exception of type 'System.IO.FileLoadException' occurred in GoogleApi.dll

Additional information: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

I am unable to do anything until I update to version 10.0 or higher for that nuget package. I was able to load it on a newer version of VS, but as I said that isn't a solution because of everyone else on my team using the older version of VS.

**Comment by vivet** [comment]
Hi 

Which package folder are you using? .net45?
And which .net version are you using with vs2012?

**Comment by histerical** [comment]
I am using .net45

**Comment by vivet** [comment]
My GoogleApi depends on v8 of Newtonsoft.Json for the net45 package.
I will look into upgrading it to v10, I suspect thats the issue.

**Comment by histerical** [comment]
Mine is telling me that Newtonsoft.Json version 10 is what is needed, as soon as I updated it to version 10, I no longer had the exception.

**Comment by vivet** [comment]
Ok good.
That could be because you have another dependency for V10. Nevertheless I
will make all nuget package compatible with that version.

**Comment by histerical** [comment]
Ok, I started a fresh project with nothing and only added your nuget package. Once I tried running it and using the places autocomplete, it broke with that exception. But thank you for looking at it.

**Comment by vivet** [comment]
ok thanks for the update.
I will probably have some time tomorrow night to make a fix, and otherwise the day after.

...and no problem for me to look into it. My pleasure.

**Comment by vivet** [comment]
Hi again.
I actually just found the issue and fixed it.
The problem occurs due to wrong dependency reference in the nuspec. I have changed that and published v3.0.3, where all packages references Newtonsoft.Json 9.0.1+

I am curious if you get the package for the portable build or actual net45 build. The former should be compatible with net45, and that was the package which was incorrect. I am asking cause possibly I can remove and stop maintaining the specific net45 build in the nuget package. 
Could you check the references in your solution and into which folder in the GoogleAPi nuget package point? I can't myself as i work on VS2017, and there are differences.

Also let me know if the latest package works for you.

**Comment by histerical** [comment]
Thanks, that was it, started a new project with nothing but the API and worked perfectly.
