### ISSUE TITLE
TravelMode.WALKING is only supported in lower case

### ISSUE THREAD

**Issue by InFany-ai** [vivet/GoogleApi#391]
TravelMode.WALKING is only supported in lower case, otherwise it is seen as DRIVING by default, making it impossible to get a route for WALKING

Can you comfirm and fix?

**Comment by vivet** [comment]
Which api, because I have recently made changes to these

**Comment by vivet** [comment]
It's a bit strange, because I recently changed it to upper-case based on this bug: https://github.com/vivet/GoogleApi/issues/386
Though, I found it strange because the Google docs has an example in UPPER_CASE and the possible values shown in lower-case.

I will do some tests, and see what seems right. But I think you are right.

@AlexGall24 can you comment based on the fix we made about a month ago? Maybe you weren't right after all

**Comment by InFany-ai** [comment]
Maybe because it was Walking, but I don't see any mention of travelMode in the screen shots

here are my queries

![3](https://github.com/vivet/GoogleApi/assets/79629807/7e5ee960-8637-418f-b191-8d473b9eb0a2)
![2](https://github.com/vivet/GoogleApi/assets/79629807/84845b73-2930-4b86-848d-f2325989cfa1)
![1](https://github.com/vivet/GoogleApi/assets/79629807/41238eba-f5bc-451c-a905-133589a67257)

**Comment by AlexGall24** [comment]
I can confirm the behavior's provided by @InFany-ai,

I'm uploading the images.

![image](https://github.com/vivet/GoogleApi/assets/102618682/26b8e28f-0da7-48e1-8415-2c99d7b6bd9d)

![image](https://github.com/vivet/GoogleApi/assets/102618682/1f91f033-17b3-4859-ac88-b09331ee7817)

**Comment by vivet** [comment]
I think I nailed it.
Sorry for the confusion around travel-mode, but it should work correctly now with lower-case in the request and upper-case in the response.

Let me know if you have further issues.
