### ISSUE TITLE
Demo project

### ISSUE THREAD

**Issue by bdkacz** [vivet/GoogleApi#88]
Hi. Can you post some demo project which  create direction between 3 points and display it on the map - the best as WPF app ?

**Comment by vivet** [comment]
Hi

Sorry I am on vacation until the 12th of March.
And sorry, but I don't have the samples you request. Try inspect the test
project, it contains several examples including directions.

Feel free to ask questions, and I will try my best to assist you.

On Mar 4, 2018 01:11, "bdkacz" <notifications@github.com> wrote:

Hi. Can you post some demo project which create direction between 3 points
and display it on the map - the best as WPF app ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/vivet/GoogleApi/issues/88>, or mute the thread

**Comment by bdkacz** [comment]
Hi.
I found in examples how to get directions,but how display it on a map ? Webbrowser component ? And what about url ?

**Comment by bdkacz** [comment]
Got it. So simple 

var url = "https://www.google.com/maps/dir/?api=1&" + result.RawQueryString;

**Comment by vivet** [comment]
Hi
Good you figured it out.
Personally, I don't work with frontends, so i wouldn't be able to help much.

If you like my project, please star it 😃
